name: play_viagens_passageiro
description: "Play Viagens - App do Passageiro"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.2.0+1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^14.2.0
  
  # Network & API
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  socket_io_client: ^2.0.3+1
  http: ^1.1.0
  
  # Push Notifications
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  
  # Payments
  flutter_stripe: ^11.2.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  
  # Utilities
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  
  # Date & Time
  intl: ^0.19.0
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Camera & QR
  mobile_scanner: ^3.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
